version: '3'
services:
  bg:
    image: huangyingting/bg
    build: 
      context: .
      dockerfile: go/app/bg/Dockerfile
    ports:
      - 8000:8000
      - 9000:9000
  bi:
    image: huangyingting/bi
    build: 
      context: .
      dockerfile: go/app/bi/Dockerfile
    ports:
      - 8001:8001
      - 9001:9001
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  be:
    image: huangyingting/be
    build: 
      context: .
      dockerfile: python/be/Dockerfile
    ports:
      - 8002:8002
  bs:
    image: huangyingting/bs
    build: 
      context: .
      dockerfile: go/app/bs/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
      etcd:
        condition: service_started
      redis:
        condition: service_started
      es:
        condition: service_started
      rabbitmq:
        condition: service_started
  mysql:
    image: mysql:5.7
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10    
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_USER=bingo
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=bingo
    ports:
      - 3306:3306
  etcd:
    image: bitnami/etcd:3.5.3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
  redis:
    image: redislabs/rebloom:latest
    ports:
      - 6379:6379
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=
      - RABBITMQ_DEFAULT_PASS=
  gowitness:
    image: huangyingting/gowitness
    ports:
      - 7171:7171