apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    ingressClassName: nginx
    hosts:
      - jaeger.cilium.i-csu.com
    tls:
      - hosts:
          - jaeger.cilium.i-csu.com
        secretName: jaeger-tls