// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.1

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type BIHTTPServer interface {
	Clicks(context.Context, *ClicksRequest) (*ClicksReply, error)
}

func RegisterBIHTTPServer(s *http.Server, srv BIHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/clicks/{alias}", _BI_Clicks0_HTTP_Handler(srv))
}

func _BI_Clicks0_HTTP_Handler(srv BIHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClicksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.bi.v1.BI/Clicks")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Clicks(ctx, req.(*ClicksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClicksReply)
		return ctx.Result(200, reply)
	}
}

type BIHTTPClient interface {
	Clicks(ctx context.Context, req *ClicksRequest, opts ...http.CallOption) (rsp *ClicksReply, err error)
}

type BIHTTPClientImpl struct {
	cc *http.Client
}

func NewBIHTTPClient(client *http.Client) BIHTTPClient {
	return &BIHTTPClientImpl{client}
}

func (c *BIHTTPClientImpl) Clicks(ctx context.Context, in *ClicksRequest, opts ...http.CallOption) (*ClicksReply, error) {
	var out ClicksReply
	pattern := "/v1/clicks/{alias}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.bi.v1.BI/Clicks"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
