// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: v1/bi_api.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClicksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias string `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *ClicksRequest) Reset() {
	*x = ClicksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_bi_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClicksRequest) ProtoMessage() {}

func (x *ClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_bi_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClicksRequest.ProtoReflect.Descriptor instead.
func (*ClicksRequest) Descriptor() ([]byte, []int) {
	return file_v1_bi_api_proto_rawDescGZIP(), []int{0}
}

func (x *ClicksRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type ClicksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clicks uint64 `protobuf:"varint,1,opt,name=clicks,proto3" json:"clicks,omitempty"`
}

func (x *ClicksReply) Reset() {
	*x = ClicksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_bi_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClicksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClicksReply) ProtoMessage() {}

func (x *ClicksReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_bi_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClicksReply.ProtoReflect.Descriptor instead.
func (*ClicksReply) Descriptor() ([]byte, []int) {
	return file_v1_bi_api_proto_rawDescGZIP(), []int{1}
}

func (x *ClicksReply) GetClicks() uint64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

type ClickEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias     string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Ip        string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Ua        string                 `protobuf:"bytes,3,opt,name=ua,proto3" json:"ua,omitempty"`
	Referer   string                 `protobuf:"bytes,4,opt,name=referer,proto3" json:"referer,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_bi_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_bi_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_v1_bi_api_proto_rawDescGZIP(), []int{2}
}

func (x *ClickEvent) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ClickEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClickEvent) GetUa() string {
	if x != nil {
		return x.Ua
	}
	return ""
}

func (x *ClickEvent) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *ClickEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_v1_bi_api_proto protoreflect.FileDescriptor

var file_v1_bi_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x31, 0x2f, 0x62, 0x69, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x43,
	0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69,
	0x61, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x22, 0x97, 0x01, 0x0a, 0x0a, 0x43, 0x6c,
	0x69, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x75, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x75, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x32, 0x5c, 0x0a, 0x02, 0x42, 0x49, 0x12, 0x56, 0x0a, 0x06, 0x43, 0x6c, 0x69,
	0x63, 0x6b, 0x73, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x73, 0x2f, 0x7b, 0x61, 0x6c, 0x69, 0x61, 0x73,
	0x7d, 0x42, 0x24, 0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x2e, 0x76, 0x31, 0x42, 0x07,
	0x41, 0x70, 0x69, 0x42, 0x49, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x0c, 0x61, 0x70, 0x69, 0x2f, 0x62,
	0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_bi_api_proto_rawDescOnce sync.Once
	file_v1_bi_api_proto_rawDescData = file_v1_bi_api_proto_rawDesc
)

func file_v1_bi_api_proto_rawDescGZIP() []byte {
	file_v1_bi_api_proto_rawDescOnce.Do(func() {
		file_v1_bi_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_bi_api_proto_rawDescData)
	})
	return file_v1_bi_api_proto_rawDescData
}

var file_v1_bi_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_bi_api_proto_goTypes = []interface{}{
	(*ClicksRequest)(nil),         // 0: api.bi.v1.ClicksRequest
	(*ClicksReply)(nil),           // 1: api.bi.v1.ClicksReply
	(*ClickEvent)(nil),            // 2: api.bi.v1.ClickEvent
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_bi_api_proto_depIdxs = []int32{
	3, // 0: api.bi.v1.ClickEvent.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: api.bi.v1.BI.Clicks:input_type -> api.bi.v1.ClicksRequest
	1, // 2: api.bi.v1.BI.Clicks:output_type -> api.bi.v1.ClicksReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_bi_api_proto_init() }
func file_v1_bi_api_proto_init() {
	if File_v1_bi_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_bi_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClicksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_bi_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClicksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_bi_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_bi_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_bi_api_proto_goTypes,
		DependencyIndexes: file_v1_bi_api_proto_depIdxs,
		MessageInfos:      file_v1_bi_api_proto_msgTypes,
	}.Build()
	File_v1_bi_api_proto = out.File
	file_v1_bi_api_proto_rawDesc = nil
	file_v1_bi_api_proto_goTypes = nil
	file_v1_bi_api_proto_depIdxs = nil
}
