server:
  http:
    addr: "${HTTP_ADDR:0.0.0.0:8080}"
    timeout: "${HTTP_TIMEOUT:1s}"
  grpc:
    addr: "${GRPC_ADDR:0.0.0.0:9090}"
    timeout: "${GRPC_TIMEOUT:1s}"
  debug: true
store:
  driver: "${DB_DRIVER:sqlite}"
  host: "${DB_HOST:}"
  port: "${DB_PORT:0}"
  database: "${DB_DATABASE:}"
  username: "${DB_USERNAME:}"
  password: "${DB_PASSWORD:}"
alias:
  start_time: 2020-01-01
  bit_len_time: 35
  bit_len_sequence: 7
  bit_len_machine_id: 5
  etcd_addr: ["localhost:2379"]
search:
  addr: ["http://localhost:9200"]
  index_name: short_url
  sniff: false
  number_of_shards: 1
  number_of_replicas: 0
cache:
  addr: localhost:6379
  cache_ttl: 3600
recaptcha:
  site_key: 6Lethl8fAAAAAMEhZak5YlwnJUetY1dLGsaDLMxK
  secret_key: 6Lethl8fAAAAAC56VodoE7eLg1hQhnMs5pP9dlbA
jwt:
  issuer: https://login.microsoftonline.com/736e8d18-4edf-4080-96b9-69afaec94892/v2.0
  audience: 52d63002-b52b-4233-a733-092896d960b6
  fallback_signature_algorithm: RS256
  required_claims:
    tid: 736e8d18-4edf-4080-96b9-69afaec94892
    scp: API.Read API.Write
publisher:
  amqp_uri: "${AMQP_URI:amqp://localhost:5672/}"
  name: clicks-publisher
  ca_cert:
  client_cert:
  client_key:
  exchange_name: bingo
  exchange_type: direct
  queue_mode: default
  routing_key: clicks
  worker_count: "${WORKER_COUNT:2}"
  prefetch_count: "${PREFETCH_COUNT:2}"
  retry_attempt: 1
  retry_interval: 1s
  connect_timeout: 5s
bi:
  grpc_addr: "${REMOTE_BI_GRPC_ADDR:localhost:9001}"
  http_addr: "${REMOTE_BI_HTTP_ADDR:localhost:8001}"
  protocol: HTTP
be:
  http_addr: "${REMOTE_BE_HTTP_ADDR:localhost:8002}"
go_witness:
  addr: "${REMOTE_GO_WITNESS_ADDR:http://localhost:7171}"  