apiVersion: v1
kind: Service
metadata:
  name: bs
  labels:
    app: bs
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: bs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bs
  labels:
    app: bs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bs
  template:
    metadata:
      labels:
        app: bs
    spec:
      containers:
      - name: bs
        image: ghcr.io/huangyingting/bs:latest
        env:
        - name: BS_DB_DRIVER
          value: mysql
        - name: BS_DB_HOST
          value: mysql.mysql
        - name: BS_DB_PORT
          value: "3306"
        - name: BS_DB_DATABASE
          value: bingo
        - name: BS_DB_USERNAME
          value: bingo
        - name: BS_DB_PASSWORD
          value: P@ssw0rd
        - name: BS_ETCD_ADDR
          value: etcd.etcd:2379
        - name: BS_ES_ADDR
          value: http://es-es-http.es:9200
        - name: BS_REDIS_ADDR
          value: redis:/:pXLNZgvIB8@redis-master.redis:6379
        - name: BS_AMQP_URI
          value: amqp://user:d2EhB1p9K4@rabbitmq.rabbitmq:5672/
        - name: BS_REMOTE_BI_HTTP_ADDR
          value: bi:8001
        - name: BS_REMOTE_BE_HTTP_ADDR
          value: be:8002
        - name: BS_REMOTE_GO_WITNESS_ADDR
          value: https://gowitness.aliases.biz
        - name: BS_JAEGER_ADDR
          value: http://jaeger-collector.jaeger:14268/api/traces
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: bs-ing
spec:
  rules:
  - host: aliases.biz
    http:
      paths:
      - backend:
          service:
            name: bs
            port:
              number: 8080
        pathType: Prefix
        path: /
  tls:
  - hosts:
    - aliases.biz
    secretName: bs-tls
