apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bs
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: bs
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - bingo
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bi
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: bi
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - bingo
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: be
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: be
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - bingo
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bg
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: bg
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - bingo