name: 'Prune untagged images'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  purge-image:
    name: Prune untagged images
    runs-on: ubuntu-latest
    steps:
      - name: Prune all untagged images
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.DELETE_PACKAGE_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: user