name: 'Prune PR images'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  purge-image:
    name: Prune PR images
    runs-on: ubuntu-latest
    steps:
      - name: Prune all PR images
        uses: snok/container-retention-policy@v1
        with:
          token: ${{ secrets.DELETE_PACKAGE_TOKEN }}
          cut-off: An hour ago UTC
          image-names: huangyingting/bs, huangyingting/be, huangyingting/bi, huangyingting/bg
          account-type: personal
          filter-tags: pr-*
