name: 'Prune images'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  purge-image:
    name: Prune images
    runs-on: ubuntu-latest
    steps:
      - name: Prune pull request image
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.DELETE_PACKAGE_TOKEN }}
          organization: huangyingting
          container: bs
          dry-run: true # Dry-run first, then change to `false`
          untagged: false
